### ISSUE TITLE
Is it possible to filter the module path?

### ISSUE THREAD

**Issue by io7m** [apache/felix-atomos#52]
The default Atomos boot layer seems to contain everything on the module path. This (obviously) includes all of the JDK and Java modules, but it also includes any other modules that a host application might be using.

If I want to write a JPMS-modularized application that dynamically creates embedded OSGi containers running Atomos, it seems as though all of the modules my JPMS host application has are also made accessible to the OSGi container. There doesn't appear to be a way to turn this off, or to filter the list of modules that end up visible in the Atomos boot layer.

For my use case, I'd be happy with an Atomos boot layer that _only_ contained the JVM's own modules. I would then create my own Atomos layer on top of that, containing only extra modules I wanted to expose to the OSGi container.

Is there some way I can do this?

**Comment by tjwatson** [comment]
See https://github.com/apache/felix-atomos#adding-layers

You would start off with your framework (Felix or Equinox), Atomos and your own module that requires Atomos on the initial module path of the JVM.  Then in you main module you would have a main method that could have code like this:

```java
    Atomos atomos = Atomos.newAtomos();
    AtomosLayer bootLayer = atomos.getBootLayer();

    // Add a layer that loads all modules contained in "modules-child1" directory
    Path modulesChild1 = new File("modules-child1").toPath();
    AtomosLayer child1 = bootLayer.addLayer("child1", LoaderType.SINGLE, modulesChild1);

    // Create a new framework to use the layers configured with Atomos
    Framework framework = atomos.newFramework(Map.of());
````

Here the `modulesChild1` is a directory and it will load all modules found in that directory, but if you want to be more selective you can pass any number of paths there to individual files that you want loaded instead of a directory full of module files.

That framework should  have all the modules contained on the JVM module path as well as the modules contained in the "modules-child1" directory.

**Comment by io7m** [comment]
I'm not sure if I'm misunderstanding what you wrote, but it seems like you're describing how to add extra modules. My problem is that I actually want to _reduce_ the set of modules that are initially available (and then add my own layers afterwards using the `addLayer` mechanism you've described). That is, I want to stop Atomos from automatically bringing in everything that was on the initial module path of the JVM.

**Comment by tjwatson** [comment]
Looks like the README needs updated in this regard because the addLayer method takes a list of parent layers.  I thought we also had a convenience method that just added it to the layer you are invoking addLayer on.

**Comment by io7m** [comment]
Hm, right, that's what I'm doing. The bundles are still being installed, however. I'll try to put together a repro case.

**Comment by io7m** [comment]
Ouch, sorry, this one turned out to be my fault: The bundles were being loaded from the Felix cache, because I'd started Atomos once without doing the above.
