### ISSUE TITLE
Modules org.eclipse.osgi and org.apache.felix.scr export package org.osgi.util.tracker to module osgi.core

### ISSUE THREAD

**Issue by RefuX** [apache/felix-atomos#73]
Not really an Atomos issue per se, but I was playing around with your example command to load everything as modules:
`java --add-modules=ALL-MODULE-PATH -p bundles -m org.apache.felix.atomos`

In my test I also used org.apache.felix.scr, and it turns out it has a split package. Is there any solution to this? I have other JPMS modules I need to be loaded as bundles, so switching to the cp won't solve the issue for me (I think)

Thanks for any insights.

**Comment by tjwatson** [comment]
Can you list the split packages?  I ask because issue https://issues.apache.org/jira/browse/FELIX-6521 I updated SCR to no longer export (or include) the `org.osgi.service.component` packages.  The latest release of SCR should only include `org.apache.felix.scr` packages, which I would not expect to be in any other bundles.

**Comment by tjwatson** [comment]
I see now that the issue title/summary states `org.osgi.util.tracker`.  I don't believe that package has been exported by the SCR bundle for a long time.  What version of SCR are you trying to use?

**Comment by RefuX** [comment]
My apologies you are correct, I was using an old scr package.
